### ISSUE TITLE
FileSystemNotFoundException when executed from jar

### ISSUE THREAD

**Issue by Johann150** [Johann150/archiver#11]
## stack trace:
```
java.nio.file.FileSystemNotFoundException
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
        at java.nio.file.Paths.get(Unknown Source)
        at archiverFX.Main.getLanguageMenu(Main.java:169)
        at archiverFX.Main.createMenu(Main.java:161)
        at archiverFX.Main.start(Main.java:99)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)
```
and then some `NullPointerException`'s due to the unfound FileSystem

**Comment by Johann150** [comment]
This has to do with the way the file system inside a jar is build up: It is compressed like a zip file, actually the compression is the same as a zip file.
